package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import modelo.DataConstants;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author raul-portatil
 */
public class CanvasJFrame extends javax.swing.JFrame implements ActionListener {

    public JButton getjButtonAgregarObstaculo() {
        return jButtonAgregarObstaculo;
    }

    public JButton getjButtonAgregarVehiculo() {
        return jButtonAgregarVehiculo;
    }

    public JButton getjButtonAgregarZonaRiesgo() {
        return jButtonAgregarZonaRiesgo1;
    }

    public JButton getjButtonIniciar() {
        return jButtonIniciar;
    }

    public JPanel getjPanelCanvas() {
        return jPanelContent;
    }

    public JPanel getjPanelTablero() {
        return jPanelTablero;
    }

    public Canvas getCanvas() {
        return c;
    }

    public JTextArea getjTextAreaLog() {
        return jTextAreaLog;
    }

    /**
     * Creates new form CanvasJFrame
     */
    public CanvasJFrame() {
        initComponents();
        this.setResizable(false);
        c = new Canvas(this.jPanelTablero.getSize(), this.jTextAreaLog);
        this.jPanelTablero.add(c);
        this.addActionListener();
        this.jTextAreaLog.setText(DataConstants.log);
    }

    /**
     * This method is called from within the constructor to runialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jPanelTablero = new javax.swing.JPanel();
        jButtonAgregarZonaRiesgo1 = new javax.swing.JButton();
        jButtonAgregarObstaculo = new javax.swing.JButton();
        jButtonAgregarVehiculo = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jButtonAgregarDestino = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonAgregarZonaRiesgo2 = new javax.swing.JButton();
        jButtonAgregarZonaRiesgo3 = new javax.swing.JButton();
        jButtonAgregarWayPoint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelTableroLayout = new javax.swing.GroupLayout(jPanelTablero);
        jPanelTablero.setLayout(jPanelTableroLayout);
        jPanelTableroLayout.setHorizontalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanelTableroLayout.setVerticalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAgregarZonaRiesgo1.setText("Añadir zona de riesgo 1");

        jButtonAgregarObstaculo.setText("Añadir Obstaculo");

        jButtonAgregarVehiculo.setText("Añadir inicio");

        jButtonIniciar.setText("Comenzar");

        jButtonAgregarDestino.setText("Añadir destino");

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        jButtonAgregarZonaRiesgo2.setText("Añadir zona de riesgo 2");
        jButtonAgregarZonaRiesgo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarZonaRiesgo2ActionPerformed(evt);
            }
        });

        jButtonAgregarZonaRiesgo3.setText("Añadir zona de riesgo 3");
        jButtonAgregarZonaRiesgo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarZonaRiesgo3ActionPerformed(evt);
            }
        });

        jButtonAgregarWayPoint.setText("Añadir WayPoint");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarZonaRiesgo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarZonaRiesgo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarZonaRiesgo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarObstaculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAgregarWayPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAgregarVehiculo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregarObstaculo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregarZonaRiesgo1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregarZonaRiesgo2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregarZonaRiesgo3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregarWayPoint)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgregarDestino)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarZonaRiesgo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarZonaRiesgo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarZonaRiesgo2ActionPerformed

    private void jButtonAgregarZonaRiesgo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarZonaRiesgo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarZonaRiesgo3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarDestino;
    private javax.swing.JButton jButtonAgregarObstaculo;
    private javax.swing.JButton jButtonAgregarVehiculo;
    private javax.swing.JButton jButtonAgregarWayPoint;
    private javax.swing.JButton jButtonAgregarZonaRiesgo1;
    private javax.swing.JButton jButtonAgregarZonaRiesgo2;
    private javax.swing.JButton jButtonAgregarZonaRiesgo3;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelTablero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables
    private Canvas c;

    @Override
    public void actionPerformed(ActionEvent ae) {

        if (this.jButtonAgregarObstaculo == ae.getSource()) {
            DataConstants.elementToAdd = DataConstants.imgObstacle;
        }
        if (this.jButtonAgregarWayPoint == ae.getSource()) {
            DataConstants.elementToAdd = DataConstants.imgWayPoint;
        } else if (this.jButtonAgregarVehiculo == ae.getSource()) {
            DataConstants.elementToAdd = DataConstants.imgPlayer;
            this.jButtonAgregarVehiculo.setEnabled(false);

        } else if (this.jButtonAgregarDestino == ae.getSource()) {
            DataConstants.elementToAdd = DataConstants.imgDestiny;
            this.jButtonAgregarDestino.setEnabled(false);

        } else if (this.jButtonIniciar == ae.getSource() && DataConstants.inicio != null && DataConstants.destino != null) {
            this.jButtonIniciar.setEnabled(false);
            DataConstants.elementToAdd = DataConstants.imgRuta;

            DataConstants.log += "\ncalculando...";
            this.jTextAreaLog.setText(DataConstants.log);

            controller.Controlador.run();
            this.jButtonIniciar.setEnabled(true);
        } else if (this.jButtonAgregarZonaRiesgo1 == ae.getSource()) {
            DataConstants.elementToAdd = DataConstants.imgRisk1;
        } else if (this.jButtonAgregarZonaRiesgo2 == ae.getSource()) {
            DataConstants.elementToAdd = DataConstants.imgRisk2;
        } else if (this.jButtonAgregarZonaRiesgo3 == ae.getSource()) {
            DataConstants.elementToAdd = DataConstants.imgRisk3;
        }

    }

    public void addActionListener() {
        this.jButtonAgregarObstaculo.addActionListener(this);
        this.jButtonAgregarVehiculo.addActionListener(this);
        this.jButtonAgregarZonaRiesgo1.addActionListener(this);
        this.jButtonAgregarZonaRiesgo2.addActionListener(this);
        this.jButtonAgregarZonaRiesgo3.addActionListener(this);
        this.jButtonIniciar.addActionListener(this);
        this.jButtonAgregarDestino.addActionListener(this);
        this.jButtonAgregarWayPoint.addActionListener(this);
    }
}
