/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import modelo.DataConstants;

/**
 *
 * @author raul-portatil
 */
public class SelectorInicialJFame extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form SelectorInicialJFame
     */
    public SelectorInicialJFame() {
        initComponents();
        this.jButtonSiguiente.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSiguiente = new javax.swing.JButton();
        jLabelFilas = new javax.swing.JLabel();
        jLabelColumnas = new javax.swing.JLabel();
        jLabelRiesgo1 = new javax.swing.JLabel();
        jLabelRiesgo2 = new javax.swing.JLabel();
        jLabelRiesgo3 = new javax.swing.JLabel();
        jLabelReduccionRiesgoPorCorteza = new javax.swing.JLabel();
        jTextFieldFilas = new javax.swing.JTextField();
        jTextFieldColumnas = new javax.swing.JTextField();
        jTextFieldRiesgo1 = new javax.swing.JTextField();
        jTextFieldRiesgo2 = new javax.swing.JTextField();
        jTextFieldRiesgo3 = new javax.swing.JTextField();
        jTextFieldReduccionPorCorteza = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSiguiente.setText("siguiente");

        jLabelFilas.setText("Filas:");

        jLabelColumnas.setText("Columnas:");

        jLabelRiesgo1.setText("Incremento de h por riesgo1:");

        jLabelRiesgo2.setText("Incremento de h por riesgo2:");

        jLabelRiesgo3.setText("Incremento de h por riesgo3:");

        jLabelReduccionRiesgoPorCorteza.setText("Reduccion del riesgo por corteza (0-0.5):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelColumnas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFilas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelRiesgo3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldRiesgo3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelRiesgo2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldRiesgo2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelRiesgo1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldRiesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelReduccionRiesgoPorCorteza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldReduccionPorCorteza, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilas)
                    .addComponent(jTextFieldFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColumnas)
                    .addComponent(jTextFieldColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRiesgo1)
                    .addComponent(jTextFieldRiesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRiesgo2)
                    .addComponent(jTextFieldRiesgo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRiesgo3)
                    .addComponent(jTextFieldRiesgo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReduccionRiesgoPorCorteza)
                    .addComponent(jTextFieldReduccionPorCorteza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelColumnas;
    private javax.swing.JLabel jLabelFilas;
    private javax.swing.JLabel jLabelReduccionRiesgoPorCorteza;
    private javax.swing.JLabel jLabelRiesgo1;
    private javax.swing.JLabel jLabelRiesgo2;
    private javax.swing.JLabel jLabelRiesgo3;
    private javax.swing.JTextField jTextFieldColumnas;
    private javax.swing.JTextField jTextFieldFilas;
    private javax.swing.JTextField jTextFieldReduccionPorCorteza;
    private javax.swing.JTextField jTextFieldRiesgo1;
    private javax.swing.JTextField jTextFieldRiesgo2;
    private javax.swing.JTextField jTextFieldRiesgo3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if (this.jTextFieldColumnas.getText().isEmpty()
                || this.jTextFieldFilas.getText().isEmpty()
                || this.jTextFieldReduccionPorCorteza.getText().isEmpty()
                || this.jTextFieldRiesgo1.getText().isEmpty()
                || this.jTextFieldRiesgo2.getText().isEmpty()
                || this.jTextFieldRiesgo3.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Tienes que rellenar todos los campos", "Advertencia",
                    JOptionPane.WARNING_MESSAGE);

        } else if (Double.valueOf(this.jTextFieldReduccionPorCorteza.getText()) >= 0.5) {
            JOptionPane.showMessageDialog(this, "El valor de la reduccion por corteza ha de ser menor que 0.5, para que exista al menos un vaor minimo en las cortezas de los puntos de riesgo", "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            DataConstants.FILAS = Integer.valueOf(this.jTextFieldFilas.getText());
            DataConstants.COLUMNAS = Integer.valueOf(this.jTextFieldColumnas.getText());
            DataConstants.riesgo1 = Integer.valueOf(this.jTextFieldRiesgo1.getText());
            DataConstants.riesgo2 = Integer.valueOf(this.jTextFieldRiesgo2.getText());
            DataConstants.riesgo3 = Integer.valueOf(this.jTextFieldRiesgo3.getText());
            DataConstants.reduccionRiesgoPorCorteza = Double.valueOf(this.jTextFieldReduccionPorCorteza.getText());
            
            DataConstants.log += 
                    "Filas: " + DataConstants.FILAS + "\n"
                    + "Columnas: " + DataConstants.COLUMNAS + "\n"
                    + "Valor riesgo1: " + DataConstants.riesgo1 + "\n"
                    + "Valor riesgo2: " + DataConstants.riesgo2 + "\n"
                    + "Valor riesgo3: " + DataConstants.riesgo3 + "\n"
                    + "ReduccionRiesgoCorteza: " + DataConstants.reduccionRiesgoPorCorteza + "\n"
                    ;
            
            controller.Controlador.init();
            this.setVisible(false);
        }
    }
}
